### ISSUE TITLE
Won't start on newer GTK versions

### ISSUE THREAD

**Issue by jamerst** [henriklaxhuber/perspektiv#5]
When trying to start perspektiv  on my Fedora 35 system I get the following error:
```
thread 'main' panicked at 'libgtk-3 was configured with `--enable-debug=no`. See https://github.com/gtk-rs/gtk/issues/270 for details', /home/jtattersall/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.4.1/src/rt.rs:146:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: <unknown>
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=1 perspektiv
```

Perspektiv worked fine on Fedora 35 initially, but it appears to have been broken by updating the GTK version from 3.24.30 to 3.24.31. Unfortunately I can't confirm this as I can't easily downgrade GTK. The same issue is present on another machine, also running Fedora 35 and the same GTK version.

**Comment by he-la** [comment]
Sorry for the delay here - somehow this issue flew under my radar this past year. The issue stems from a limitation in the GTK wrapper lib that I am using. This lib is now deprecated and its replacement appears to not suffer from the same issue (though I haven't tested yet).

Will fix, but it means I need to do some rewriting of the internals.
